### ISSUE TITLE
Missing error handling

### ISSUE THREAD

**Issue by m-aciek** [tareq1988/wp-generators#3]
Hello,
I'd like to report that in CRUD generated validation is silent – if there is problem with data, item doesn't save without any message in admin panel.

Regards,
Maciej

**Comment by tareq1988** [comment]
By implementation its that way, I haven't handled validation as it might differ in various situation. If the plugin developers think they need something, they should implement that validation. Its a quick way to generate code to get started.

If you think you can add that feature to the generator, any pull requests are welcome :)

**Comment by m-aciek** [comment]
I've improved a bit error handling. Please check my pull requests.
